name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./app-for-my-mom

      - name: Build project
        run: npm run build
        working-directory: ./app-for-my-mom

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          folder: ./app-for-my-mom/dist
          branch: gh-pages